### ISSUE TITLE
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false breaks completion menu

### ISSUE THREAD

**Issue by romkatv** [Powerlevel9k/powerlevel9k#1267]
This is on `master`.

To reproduce:

1. Enable completion menu.
2. Resize your terminal so that it has fewer than 20 lines (confirm with `echo $LINES`).
3. Set `POWERLEVEL9K_PROMPT_ON_NEWLINE=true` and `POWERLEVEL9K_RPROMPT_ON_NEWLINE=false`.
4. Type `grep --` and press `TAB` twice.

Steps 1-3 more precisely (you still need to type `grep --` and press `TAB` twice once ZSH prompt appears):

```zsh
docker run -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -e TERM=$TERM -it --rm ubuntu bash -uexc '
  cd
  apt update && apt install -y zsh git
  git clone https://github.com/bhilburn/powerlevel9k.git
  echo "
    zstyle :completion:\* menu yes select
    autoload -Uz compinit && compinit
    POWERLEVEL9K_PROMPT_ON_NEWLINE=true
    POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
    source ~/powerlevel9k/powerlevel9k.zsh-theme" >~/.zshrc
  exec zsh'
```

Actual behavior:

![actual](https://user-images.githubusercontent.com/1282067/57519197-04010e00-731b-11e9-81ab-05d92fed03e6.png)

Expected behavior:

![expected](https://user-images.githubusercontent.com/1282067/57519209-0a8f8580-731b-11e9-83a6-9e6ca4150128.png)

**Comment by dritter** [comment]
Fixed on `next` with #1335
