### ISSUE TITLE
TRANSIENT_RPROMPT is not respected

### ISSUE THREAD

**Issue by romkatv** [Powerlevel9k/powerlevel9k#1291]
To reproduce:

```zsh
docker run -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -e TERM=$TERM -it --rm ubuntu bash -uexc '
  cd
  apt update && apt install -y zsh git
  git clone https://github.com/bhilburn/powerlevel9k.git
  echo "
    setopt TRANSIENT_RPROMPT
    POWERLEVEL9K_PROMPT_ON_NEWLINE=true
    source ~/powerlevel9k/powerlevel9k.zsh-theme" >~/.zshrc
  exec zsh'
```

Then press `<enter>` a few times.

Expected: right prompt is displayed only for the last (active) prompt.
Actual: right prompt is displayed even for the past prompts.

Note: Adding `POWERLEVEL9K_RPROMPT_ON_NEWLINE=true` to the config fixes the issue.

**Comment by dritter** [comment]
Fixed on `next` with #1335
