### ISSUE TITLE
dir leaks termcap sequences

### ISSUE THREAD

**Issue by romkatv** [Powerlevel9k/powerlevel9k#1310]
To reproduce:

```zsh
docker run -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -e TERM=$TERM -it --rm ubuntu bash -uexc '
  cd
  apt update && apt install -y zsh git
  git clone https://github.com/bhilburn/powerlevel9k.git
  mkdir "\033[2J\033[3J"
  cd "\033[2J\033[3J"
  echo "
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir)
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
    source ~/powerlevel9k/powerlevel9k.zsh-theme" >~/.zshrc
  exec zsh'
```

Expected:

![expected](https://user-images.githubusercontent.com/1282067/59567661-b93c8980-9070-11e9-8804-802483b26756.png)

Actual:

![actual](https://user-images.githubusercontent.com/1282067/59567647-6fec3a00-9070-11e9-8394-c4d38b3295ec.png)

**Comment by dritter** [comment]
This is now fixed on next by merging #1329 and #1340
