### ISSUE TITLE
Python virtualenv widget ignores colors

### ISSUE THREAD

**Issue by mavam** [Powerlevel9k/powerlevel9k#1351]
I'm having trouble with the configuration of the Python virtual env widget. Color settings seem to get ignored.

This issue describe the problem in detail: https://github.com/mavam/dotfiles/issues/8.

The actual bug seems to be that the color definitions don't work. Here's an example:

```
POWERLEVEL9K_PYTHON_ICON_BACKGROUND="clear"
POWERLEVEL9K_PYTHON_ICON_FOREGROUND="cyan"
```

Foreground and background are flipped, but flipping the two values of these variables don't have an effect.

This issue occurs with the latest version of powerlevel9k, zsh 5.7.1, and has been experienced on macOS.

**Comment by romkatv** [comment]
If you are using `virtualenv` prompt segment:

```zsh
POWERLEVEL9K_VIRTUALENV_BACKGROUND="clear"
POWERLEVEL9K_VIRTUALENV_FOREGROUND="cyan"
```

For `pyenv`:

```zsh
POWERLEVEL9K_PYENV_BACKGROUND="clear"
POWERLEVEL9K_PYENV_FOREGROUND="cyan"
```

For `anaconda`:

```zsh
POWERLEVEL9K_ANACONDA_BACKGROUND="clear"
POWERLEVEL9K_ANACONDA_FOREGROUND="cyan"
```

**Comment by mavam** [comment]
Thanks, that works! I must have had outdated variable names.
