### ISSUE TITLE
Trouble with multiline prefixes

### ISSUE THREAD

**Issue by stevepentland** [Powerlevel9k/powerlevel9k#1361]
Hi and let me start with saying thanks for powerlevel9k!

I'm currently having issues with the multiline prompt prefixes and I'm not sure what I'm doing wrong. It feels like I must just be missing something small but I'm stumped. I've gone through the other issues on this repo related to multiline, but with no luck.

I'm using latest `master` of p9k, with oh-my-zsh (latest), and zsh 5.7.1 in both Gnome terminal 3.32.2 and tilix 1.9.1. Font in use is `Fira Mono Nerd Font Regular`

My `.zshrc` contents:
```
export TERM="xterm-256color"
export ZSH="/home/steve/.oh-my-zsh"
POWERLEVEL9K_MODE='nerdfont-complete'
ZSH_THEME="powerlevel9k/powerlevel9k"
plugins=(gitfast git docker docker-compose)
source $ZSH/oh-my-zsh.sh
alias grep='rg'
source '/etc/profile'
```

And my configs specific to p9k are as follows:
```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs node_version rust_version go_version virtualenv newline)
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="╭"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="╰\uF460\uF460\uF460 "
POWERLEVEL9K_NODE_VERSION_BACKGROUND='172'
POWERLEVEL9K_NODE_VERSION_FOREGROUND='000'
POWERLEVEL9K_VIRTUALENV_BACKGROUND='022'
POWERLEVEL9K_VIRTUALENV_FOREGROUND='046'
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_GO_VERSION_FOREGROUND='000'
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_DELIMITER=..
```

For some reason, no matter what I do, the values specified in `POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX` and `POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX` refuse to show up. I've made sure my terminal will show the specified characters via `echo` and they output as expected.

I know I must have just overlooked something, any advice is appreciated!

**Comment by romkatv** [comment]
Parameters such as `POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX` have no effect unless `POWERLEVEL9K_PROMPT_ON_NEWLINE` is set to `true`. See https://github.com/Powerlevel9k/powerlevel9k/issues/1362.

**Comment by stevepentland** [comment]
> Parameters such as `POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX` have no effect unless `POWERLEVEL9K_PROMPT_ON_NEWLINE` is set to `true`. See #1362.

That was exactly it! Thanks @romkatv
