### ISSUE TITLE
Right Prompt Not showing at All

### ISSUE THREAD

**Issue by G5Becks** [Powerlevel9k/powerlevel9k#1367]
Hi, thanks for the wonderful theme. I am not filing  a bug because I am not 100% sure if this is something going on wrong on my end of things or not.

I am running fedora 30  and initially, when I installed the theme the right prompt was showing without any issue. Then, I installed a Gtk theme and the right prompt has disappeared. I haven't changed any setting of anything. Is this normal?

Not sure why a gtk theme would affect things in that way, but after installing the theme is when the right prompt stopped showing.

Here are my .zshrc setting if that helps. 

Thanks.

```
ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND="black"
POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND="white"
POWERLEVEL9K_LOAD_WARNING_BACKGROUND="black"
POWERLEVEL9K_LOAD_WARNING_FOREGROUND="white"
POWERLEVEL9K_LOAD_NORMAL_BACKGROUND="black"
POWERLEVEL9K_LOAD_NORMAL_FOREGROUND="white"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="red"
POWERLEVEL9K_LOAD_CRITICAL_VISUAL_IDENTIFIER_COLOR="red"
POWERLEVEL9K_LOAD_WARNING_VISUAL_IDENTIFIER_COLOR="yellow"
POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_COLOR="green"
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status history date load battery)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs ssh os_icon)
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="▶ "
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_CUSTOM_FEDORA_ICON_BACKGROUND=069
POWERLEVEL9K_CUSTOM_FEDORA_ICON_FOREGROUND=015
POWERLEVEL9K_CONTEXT_TEMPLATE=@%n

plugins=(git
	zsh-autosuggestions
	zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh
```

**Comment by romkatv** [comment]
The most common reason for missing right prompt is misconfigured `TERM`. What does `echo $TERM` say?

If `TERM` looks reasonable, type `zsh -f` to start zsh without sourcing configs from your home directory. You'll see the default prompt. Now type `RPROMPT='<<<'`. Do you see right prompt?

**Comment by G5Becks** [comment]
```
 echo $TERM
xterm-256color

```

I executed the second command and the prompt did show, but when I exit and restart the terminal, the right prompt is still not showing again.

**Comment by romkatv** [comment]
> I executed the second command and the prompt did show...

This means it's something in your configs that breaks it. Try the following. Open `~/.zshrc` and comment out the line that sets `ZSH_THEME`. Append these lines at the end of the file:

```zsh
PROMPT='%m%# '
RPROMPT='<<<'
```

Save `~/.zshrc` and restart zsh. Do you see right prompt?

**Comment by G5Becks** [comment]
Yes, its showing.

**Comment by G5Becks** [comment]
Hey, I figured out what line it was. Didn't even notice that I had this line in my config.

**`POWERLEVEL9K_DISABLE_RPROMPT=true`**

Lol, thanks for the help.

**Comment by romkatv** [comment]
LOL, I didn't notice it either.

> Then, I installed a Gtk theme and the right prompt has disappeared. I haven't changed any setting of anything.

Reminder to myself: Don't trust, verify.
