### ISSUE TITLE
Theme not applying properly [Ghostwheel]

### ISSUE THREAD

**Issue by TheHussein** [Powerlevel9k/powerlevel9k#1388]
#### Describe Your Issue
What is happening?

Icons arent showing, theme isnt being applied properly:
<img width="680" alt="Screen Shot 2019-12-18 at 1 01 37 PM" src="https://user-images.githubusercontent.com/28165176/71080944-d9234600-2196-11ea-9dc5-945999c8557e.png">

The result should be close to this:
https://raw.githubusercontent.com/sevenfoxes/dotfiles/master/ghostwheel.png

#### Have you tried to debug or fix it?
Changing the source ~/.theme line to theme2 or so gives an error that it couldnt find it and uses the default powerline which works fine, therefore it is being technically applied, just not properly, this is the ghostweel theme which is the second featured one on show your config.

#### Environment Information

This information will help us understand your configuration.

  - What version of ZSH are you using? You can use `zsh --version` to see this.
5.7.1
  - Do you use a ZSH framework (e.g., Oh-My-ZSH, Antigen)?
Antigen
  - How did you install P9k (cloning the repo, by tarball, a package from your OS, etc.,)?
brew
  - What version of P9k are you using?
Just installed with homebrew today so latest.
  - Which terminal emulator do you use?
HyperjS, but the issue persists with iterm2 and vscode terminal aswell, set font to nerd-fonts Fira Code on all, but also tried using various powerline fonts.

#### Issues with Fonts & Icons
You may delete this section if your issue is not font / icon related.

  - Which font do you use?
Fira Code
  - Which [font configuration mode](https://github.com/bhilburn/powerlevel9k/wiki/About-Fonts) are you using? You can check this with (`echo $POWERLEVEL9K_MODE`).
nerdfont-complete
  - Please share the contents of `$P9k/debug/font-issues.zsh`.
cd $P9k/debug
cd: no such file or directory: /debug
 - If this is an icon problem, does the output of `$ get_icon_names` look correct?
its giving a long list of icon names, but 90% of which it's a line with a name: {square icon}
like this
POWERLEVEL9K_BACKGROUND_JOBS_ICON:  

this is the .theme file
https://raw.githubusercontent.com/sevenfoxes/dotfiles/master/.theme

and this is my .zshrc file
```
########################
# Antigen
########################
source /usr/local/share/antigen/antigen.zsh
source ~/.theme

antigen use oh-my-zsh
antigen bundle brew
antigen bundle command-not-found
antigen bundle heroku
antigen bundle git
antigen bundle yarn
antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme bhilburn/powerlevel9k powerlevel9k
antigen apply
```

**Comment by TheHussein** [comment]
The icons issue was fixed by removing my fira code and installing FuraCode Nerd Font through
brew cask install font-firacode-nerd-font  

However, the coloring is still not the one in the theme:
<img width="680" alt="Screen Shot 2019-12-18 at 1 47 52 PM" src="https://user-images.githubusercontent.com/28165176/71084034-0ecb2d80-219d-11ea-8f89-b0c17e39e7b3.png">

**Comment by romkatv** [comment]
The config you are using is owned and maintained by https://github.com/sevenfoxes. If it doesn't work as you expect, you could try opening an issue at https://github.com/sevenfoxes/dotfiles/issues.
