### ISSUE TITLE
Does this theme also manage the colors of files and directories from ls -G?

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [Powerlevel9k/powerlevel9k#1390]
When I run `ls -G ` (enable colorized output in `ls`) I see files and folders with different colors.

Does this theme (or for that matter `Oh-my-zsh`)  manage those colors? Or does it only govern e.g. the prompt?

It is my understanding that the `LS_COLORS` variable is responsible for those colors, but I'm not sure if oh-my-zsh or this theme specifically already customize this variable.

**Comment by romkatv** [comment]
> Does this theme also manage the colors of files and directories from ls -G?

No.

> or for that matter `Oh-my-zsh`

Oh My Zsh does set `LS_COLOR`. See https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/theme-and-appearance.zsh. All files under `lib` get sourced when your source `$ZSH/oh-my-zsh.sh`. You can disable it with `DISABLE_LS_COLORS=true`.

**Comment by amelio-vazquez-reina** [comment]
Thanks @romkatv ! And do you know if themes in general (not necessarily `powerlevel9k`) may manage that variable? Or is this something relatively universal (oh-my-zsh themes are not meant to manage that variable)

**Comment by romkatv** [comment]
> And do you know if themes in general (not necessarily `powerlevel9k`) may manage that variable?

Yes, some themes do. See https://github.com/ohmyzsh/ohmyzsh/search?q=LS_COLORS&unscoped_q=LS_COLORS.

**Comment by amelio-vazquez-reina** [comment]
Awesome. Thanks @romkatv !
