### ISSUE TITLE
[Performance]

### ISSUE THREAD

**Issue by iomari** [Powerlevel9k/powerlevel9k#1393]
greetings,
my left prompt context menu is not showing at all. But when I'm logged in as root it shows. I have the same settings for both privilege and normal user:

here is the image. The top prompt is the normal user with no context segment.
The bottom is when I "su -l". There you'll see the context. Below is the relevant section of the ~/.p10k.zsh file:

https://imagebin.ca/v/58trJKQg85Hs

570   ##################################[ context: user@hostname ]##################################
  571   # Default context color.
  572   typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND='white'
  573   typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND='darkred'
  574   # Default context format: %n is username, %m is hostname.
  575   # typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n at %m'
  576   typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  577 
  578   # Context color when running with privileges.
  579   typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='darkred' 
  580   typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND='white'  
  581   # Context format when running with privileges: %n is username, %m is hostname.
  582   # typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n at %m'
  583   typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n@%m'

**Comment by romkatv** [comment]
Does this help? https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-add-username-andor-hostname-to-prompt

P.S.

In the future please open issues at https://github.com/romkatv/powerlevel10k. powerlevel9k and powerlevel10k are different projects.

**Comment by iomari** [comment]
thank you
