### ISSUE TITLE
Does make sense to have POWERLEVEL9K__[plugin_name]_[BG|FG]_COLOR variables?

### ISSUE THREAD

**Issue by davidmpaz** [Powerlevel9k/powerlevel9k#1395]
Hi 👋,

this issue is related to #1349 and i think i am just missing how to connect the dots.

thanks in advance
David

#### Describe Your Issue
Like in here:
https://github.com/Powerlevel9k/powerlevel9k/blob/v0.6.7/powerlevel9k.zsh-theme#L1638

Colors, Background and Foreground colors are somehow hardcoded. So that's why the question: is that an overkill for the theme to have so many customization variables? Makes that sense to have? Is there a better solution for this?

#### Have you tried to debug or fix it?

I have solved that for the virtualenv plugin by changing the line to:
```
"$1_prompt_segment" "$0" "$2" "$POWERLEVEL9K_VIRTUALENV_BG_COLOR" "$POWERLEVEL9K_VIRTUALENV_FG_COLOR" "${virtualenv_path:t}" 'PYTHON_ICON'
```
then in a configuration file i export all those variables for the theme to configure it. 

I could make a pull request for that, with as much plugins as possible providing default values as it is now.

#### Environment Information

  - What version of ZSH are you using? You can use `zsh --version` to see this.

```
zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

  - Do you use a ZSH framework (e.g., Oh-My-ZSH, Antigen)?

Oh-My-ZSH

  - How did you install P9k (cloning the repo, by tarball, a package from your OS, etc.,)?

cloned into: `~/.oh-my-zsh/custom/themes/powerlevel9k`

  - What version of P9k are you using?

c4a8118 (tag: v0.6.7)

  - Which terminal emulator do you use?

iTerm

**Comment by romkatv** [comment]
Try this:

```zsh
POWERLEVEL9K_VIRTUALENV_FOREGROUND=red
POWERLEVEL9K_VIRTUALENV_BACKGROUND=yellow

```

**Comment by davidmpaz** [comment]
Perfect!! Thanks for your help!!

**Comment by romkatv** [comment]
You are welcome.
