### ISSUE TITLE
Is it possible to only add a newline if vcs is present?

### ISSUE THREAD

**Issue by terryupton** [Powerlevel9k/powerlevel9k#1397]
I currently have my config like so:
```
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    os_icon                 # os identifier
    dir                     # current directory
    # =========================[ Line #2 ]=========================
    newline                 # \n
    vcs                     # git status
    # =========================[ Line #3 ]=========================
    newline                 # \n
    prompt_char             # prompt symbol
  )
```

This works nicely if there is VCS (git) present wirhin the current path.
However, an empty line appears if not.

Is there a way to check and only add a new line if VCS exists?

See below:
**Empty Line**
<img width="882" alt="Screenshot 2020-02-16 at 14 27 35" src="https://user-images.githubusercontent.com/5698596/74606486-a62efd00-50c8-11ea-8c72-c61195827aa5.png">

**Ok if in a directory with Git**
<img width="882" alt="Screenshot 2020-02-16 at 14 27 39" src="https://user-images.githubusercontent.com/5698596/74606491-b47d1900-50c8-11ea-905e-c24208d30932.png">

**Comment by romkatv** [comment]
If you are using Powerlevel10k, please file an issue against Powerlevel10k.

**Comment by romkatv** [comment]
FTR: Issue in Powerlevel10k: https://github.com/romkatv/powerlevel10k/issues/504.
