### ISSUE TITLE
Hide a part of current working directory

### ISSUE THREAD

**Issue by TerensTare** [Powerlevel9k/powerlevel9k#1402]
I just finished installing powerlevel9k on my Windows machine using WSL.
The problem is that the current working directory is shown as /mnt/c/somedir.
Is there any way to change that to just c\somedir ??

**Comment by romkatv** [comment]
Not with, powerlevel9k, no.

**Comment by TerensTare** [comment]
@romkatv What can I do to achieve that on Ubuntu ( that's the distro I use with WSL).

**Comment by romkatv** [comment]
On this forum it's only allowed to answer a slight variation of your question: "What can I do to achieve that on Ubuntu **with powerlevel9k**?" The answer is that you cannot achieve this with powerlevel9k. It's against the code of conduct of this project to answer your original question.

**Comment by TerensTare** [comment]
I understand. I'm sorry for breaking the code of conduct. I thank you for all your effort. Happy coding!

**Comment by romkatv** [comment]
You didn't break the code of conduct. Asking questions is allowed. It's only disallowed to answer them if the offered solution doesn't involve the use of powerlevel9k. That's my understanding of the rule at least.
